apiVersion : apps/v1
kind: Deployment
metadata:
  name: "kgclustertp-4539"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "kgclustertp-4539"
  template:
    metadata:
      labels:
        app: "kgclustertp-4539"
    spec:
      containers:
        - name: "kgclustertp-4539"
          image: "acrdemotp.azurecr.io/kgclustertp"
          ports:
          - containerPort: 80